include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    no_runtimeType_toString: false 
    unrelated_type_equality_checks: false
    
    

